[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Serial Monitor
monitor_speed = 115200

; Library yang dibutuhkan
lib_deps =
    tzapu/WiFiManager @ ^2.0.16-rc.2
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32

; WAJIB untuk Firebase RTDB
build_flags =
    -D ENABLE_RTDB