; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
; 1. Mengatur baud rate serial monitor sesuai dengan Serial.begin(115200)
monitor_speed = 115200

; 2. Mengunduh library secara otomatis
lib_deps =
    ; Library untuk WiFiManager
    tzapu/WiFiManager @ ^2.0.16-rc.2
    
    ; Library untuk LCD I2C
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4